# WifiNodeCost.srv
# tircgo_1107
# topic of controller -> wifi: "robot_wifi_nodecost_outer"
# topic of controller <- wifi: "robot_wifi_nodecost_inner"
RouteNode target
---
string error_code
float64 cost